getgenv().ConfigsKaitun = {
	Beta_Fix_Data_Sync = true,
	NoDeletePlayer = false,

	["Block Pet Gift"] = false,

	Collect_Cooldown = 90, -- cooldown to collect fruit

	["Low Cpu"] = true,
	["Auto Rejoin"] = false,

	["Rejoin When Update"] = false,

	Ascend = {
		Enabled = false,
		Max_Rebirth_Money = 1_000_000_000_000,
		Shop = {
			"Egg Capacity"
		}
	},

	["Limit Tree"] = {
		["Limit"] = 400,
		["Destroy Untill"] = 400,

		["Safe Tree"] = {
			"Moon Blossom",
			"Fossilight",
			"Hinomai",
			"Monoblooma",
			"Princess Thorn",
			["Serenity"] = 10,
			["Ember Lily"] = 10,
			["Sugar Apple"] = 10,
			["Burning Bud"] = 10,
			["Giant Pinecone"] = 10,
			["Elder Strawberry"] =10,
			["Beanstalk"] = 10,
			["Grand Tomato"] = 10,
			["King Cabbage"]= 10,
			["Wispwing"]= 5,
			["Romanesco"] = 3,
			["Tomato"] = 3,
			["Corn"] = 3,
			["Pumpkin"] = 3,
			["Watermelon"] = 3,
			["Strawberry"] = 3,
			["Coconut"] = 3,
			["Mushroom"] = 3,
			["Glowthorn"] = 8,
			["Apple"] = 3,
			["Orange Tulip"] = 3,
			["Blueberry"] = 3,
			["Cacao"] = 3,
			["Grape"] = 3,
			["Dragon Fruit"] = 12,
			["Blueberry"] = 12,
			["Blueberry"] = 12,
			["Bamboo "] = 4,
			["Cactus"] = 3,
			["Mango"] = 12,
			["Pepper"] = 3,
			["Lightshoot"] = 3,
			["Daffodil"] = 3,
			["Sunbulb"] = 8,
			-- for the event
			["Evo Beetroot I"] = 20,
			["Evo Blueberry I"] = 20,
			["Evo Pumpkin I"] = 20,
			["Evo Mushroom I"] = 20,
			["Evo Beetroot II"] = 20,
			["Evo Blueberry II"] = 20,
			["Evo Pumpkin II"] = 20,
			["Evo Mushroom II"] = 20,
			["Evo Beetroot III"] = 20,
			["Evo Blueberry III"] = 20,
			["Evo Pumpkin III"] = 20,
			["Evo Mushroom III"] = 20,
			["Evo Beetroot IV"] = 20,
			["Evo Blueberry IV"] = 20,
			["Evo Pumpkin IV"] = 20,
			["Evo Mushroom IV"] = 20,
		}
	},
	

	Seed = {
		Buy = {
			Mode = "Auto", -- Custom , Auto
			Custom = {
				"Carrot",
				"Bamboo",
				"Mushroom",
				"Tomato",
				"Strawberry",
				"Cactus",
				"Pepper",
				"Mango",
				"Dragon Fruit",
				"Cacao",
				"Beanstalk",
				"Grape",
				"Sugar Apple",
				"Burning Bud",
				"Orange Tulip",
				"Daffodil",
				"Mango",
				"Giant Pinecone",
				"Elder Strawberry",
				"Ember Lily",
				"Romanesco",
			}
		},
		Place = {
			Mode = "Lock", -- Select , Lock
			Select = {
				"Carrot",
				"Bamboo",
				"Ember Lily",
				"Sugar Apple",
				"Burning Bud",
				"Giant Pinecone",
				"Elder Strawberry",
				"Beanstalk",
				"Grand Tomato",
				"King Cabbage",
				"Wispwing",
				"Romanesco",
				"Tomato",
				"Corn",
				"Pumpkin",
				"Watermelon",
				"Strawberry",
				"Coconut",
				-- "Mushroom",
				"Glowthorn",
				"Apple",
				"Orange Tulip",
				"Blueberry",
				"Coconut",
				"Cacao",
				"Grape",
				"Dragon Fruit",
				"Grape",
				"Cactus",
				"Mango",
				"Pepper",
				"Lightshoot",
				"Daffodil",
				"Sunbulb",
			},
			Lock = {
				"Maple Apple",
				"Sunflower",
				"Dragon Pepper",
				"Elephant Ears",
				"Moon Melon",
				"Easter Egg",
				"Moon Mango",
				"Bone Blossom",
				"Fossilight",
				"Strawberry",
				"Mushroom"
			}
		}
	},

	["Seed Pack"] = {
		Locked = {
			["Enchanted Seed Packs"] = 5,
		}
	},

	Events = {
		MaxMoney_Restocks = 100_000_000,
		Shop = { -- delete -- to buy
			"Evo Beetroot I",
			"Evo Blueberry I",
			"Evo Pumpkin I",
			"Evo Mushroom I",
		},
		["Traveling Shop"] = {
			"Bee Egg",
			"Paradise Egg", 
			"Rare Summer Egg", 
			"Common Summer Egg"
		},
		Craft = {
			"Enchanted Chest",
			"Fairy Net",
			"Enchanted Egg",
			"Enchanted Seed Pack",
			"Anti Bee Egg",
			"Pet Shard GiantBean",
			"Sprout Egg",
		},
		Start_Do_Honey = 2_000_000 -- start trade fruit for honey at money
	},

	Gear = {
		Buy = { 
			"Grandmaster Sprinkler",
			"Master Sprinkler",
			"Godly Sprinkler",
			"Advanced Sprinkler",
			"Basic Sprinkler",
			"Lightning Rod",
			"Level Up Lollipop",
			"Levelup Lollipop",
			"Medium Treat",
			"Medium Toy",
			"Harvest Tool",
			"Watering Can"
		},
		Lock = {
			"Grandmaster Sprinkler",
			"Master Sprinkler",
			"Godly Sprinkler",
			"Advanced Sprinkler",
			"Basic Sprinkler",
			"Lightning Rod",
			"Level Up Lollipop",
			"Levelup Lollipop",
			"Mega Lollipop",
		},
	},

	Eggs = {
		Place = {
			"Jungle Egg",
			"Rare Egg",
			"Bug Egg",
			"Enchanted Egg",
			"Zen Egg",
			"Paradise Egg",
			"Sprout Egg",
			"Primal Egg",
			"Dinosaur Egg",
			"Oasis Egg",
			"Anti Bee Egg",
			"Night Egg",
			"Bee Egg",
			"Gourmet Egg",
			"Mythical Egg",
			"Fall Egg",
			-- "Rare Summer Egg",
			-- "Common Egg",
		},
		Buy = {
			"Bug Egg",
			"Night Egg",
			"Bee Egg",
			"Anti Bee Egg",
			"Paradise Egg",
			"Oasis Egg",
			"Rare Egg",
			-- "Uncommon Egg",
			"Rare Summer Egg",
			"Common Egg",
		}
	},

	Pets = {
		MutationPet = {
			["Sunny-Side Chicken"] = { "Glimmering","Rainbow" },
			["Seal"] = { "Glimmering","Rainbow" }
		},
		["Auto Feed"] = true,
		["Start Delete Pet At"] = 50,
		Unfavorite_AllPet = false,
		Favorite_LockedPet = true,
		["Upgrade Slot"] = {
			["Pet"] = {
				["Ostrich"] = { 1, 75 ,1},
				["Tanchozuru"] = { 1, 45 ,2},
				["Kodama"] = { 1, 65 ,1},
				["Corrupted Kodama"] = { 1, 65 ,1},
				["Mochi Mouse"] = { 1, 60 ,1},
				["Junkbot"] = { 1, 45 ,1},
				["Koi"] = { 1, 60 ,1},
				["Hotdog Daschund"] = { 1, 75 ,1},
				["Sunny-Side Chicken"] = { 1, 85 ,1 , true},
				["Seal"] = { 1, 75 ,1 },
				["Rooster"] = { 1, 45 ,1 },
				["Lemon Lion"] = { 1, 60 ,1},
				["Glimmering Sprite"] = { 1, 70 , 1},
				["Grizzly Bear"] = { 1, 70 , 1},
			},
			["Limit Upgrade"] = 5,
			["Equip When Done"] = {
				["Kodama"] = { 1, 70 },
				["Corrupted Kodama"] = { 1, 70 },
				["Koi"] = { 1, 70 },
				["Ostrich"] = { 2, 100, 1 },
				["Tanchozuru"] = { 1, 70 },
				["Mochi Mouse"] = { 1, 70 },
				["Junkbot"] = { 1, 70 },
				["Hotdog Daschund"] = { 1, 75 },
				["Sunny-Side Chicken"] = { 1, 100 ,1},
				["Seal"] = { 1, 75 ,1},
				["Rooster"] = { 1, 85 ,1},
				["Lemon Lion"] = { 1, 100 ,1},
				["Glimmering Sprite"] = { 1, 70 , 1},
				["Grizzly Bear"] = { 1, 70 , 1},
			},
		},
		Locked_Pet_Age = 100, -- pet that age > 60 will lock
		Locked = {
			"Dragonfly",
			"Raccoon",
			"Queen Bee",
			"Disco Bee",
			"Butterfly",
			"Mimic Octopus",
			"Fennec Fox",
			"T-Rex",
			"Spinosaurus",
			"Kitsune",
			"Corrupted Kitsune",
			"French Fry Ferret",
			"Lobster Thermidor",
			"Brontosaurus",
			"Golden Goose",
			"Cockatrice",
			"Phoenix",
			"Swan",
			["Grizzly Bear"] = 2,
			["Glimmering Sprite"] = 2,
			["Rooster"] = 2,
			["Ostrich"] = 3,
			["Seal"] = 2,
			["Hotdog Daschund"] = 1,
			"Red Panda",
			"Tiger",
		},
		LockPet_Weight = 7, -- if Weight >= 10 they will locked,
		Instant_Sell = {		
			"Chicken",
			"Kiwi",
			"Blood Kiwi",
			"Dog",
			"Golden Lab",
			"Bunny",
			"Black Bunny",
			"Cat",
			"Orange Tabby",
			"Deer",
			"Spotted Deer",
			"Monkey",
			"Silver Monkey",
			"Pig",
			"Turtle",
			"Cow",
			"Polar Bear",
			"Panda",
			"Sea Otter",
			"Hedgehog",
			"Mole",
			"Frog",
			"Grey Mouse",
			"Brown Mouse",
			"Red Giant Ant",
			"Bee",
			"Honey Bee",
			"Wasp",
			"Tarantula Hawk",
			"Moth",
			"Peacock",
			"Meerkat",
			"Sand Snake",
			"Axolotl",
			"Flamingo",
			"Sea Turtle",
			"Orangutan",
			"Seal",
			"Moon Cat",
			"Hedgehog",
			"Mole",
			"Frog",
			"Echo Frog",
			"Night Owl",
			"Petal Bee",
			"Bear Bee",
			"Hyacinth Macaw",
			"Pterodactyl",
			"Triceratops",
			"Raptor",
			"Stegosaurus",
			"Ankylosaurus",
			"Pachycephalosaurus",
			"Iguanodon",
			"Parasaurolophus",
			"Caterpillar",
			"Snail",
			"Giant Ant",
			"Praying Mantis",
			"Shiba Inu",
			"Tanuki",
			"Nihonzaru",
			"Kappa",
			"Capybara",
			"Maneki-neko",
			"Football",
			"Scarlet Macaw",
			"Bagel Bunny",
			"Pancake Mole",
			"Sushi Bear",
			"Toucan",
			"Bacon Pig",
			"Spaghetti Sloth",
			"Gorilla Chef",
			"Dairy Cow",
			"Jackalope",
			"Seedling",
			"Golem",
			"Mandrake",
			"Elk",
			"Ladybug",
			"Pixie",
			"Imp",
			"Glimmering Sprite",
			"Rooster",
			"Ostrich",
			"Cardinal",
			"Shroomie",
			"Robin",
			"Badger",
			"Grizzly Bear",
			"Hotdog Daschund",
			"Barn Owl"
			"Hummingbird",
			"Iguana",
			"Chimpanzee",
			"Tree Frog"
		}
	},

	Webhook = {
		UrlPet = getgenv().Discord,
		UrlSeed = getgenv().Discord,
		PcName = getgenv().PCAYA,

		Noti = {
			Seeds = {
			},
			SeedPack = {
			},
			Pets = {
				"Dragonfly",
				"Raccoon",
				"Queen Bee",
				"Disco Bee",
				"Butterfly",
				"Mimic Octopus",
				"Fennec Fox",
				"T-Rex",
				"Spinosaurus",
				"Kitsune",
				"Corrupted Kitsune",
				"French Fry Ferret",
				"Golden Goose",
				"Cockatrice",
				"Phoenix",
				"Swan",
				"Tiger",
			},
			Pet_Weight_Noti = true,
		}
	},
}
License = getgenv().KeyAYA
loadstring(game:HttpGet('https://raw.githubusercontent.com/Real-Aya/Loader/main/Init.lua'))()
