getgenv().ConfigsKaitun = {
	Beta_Fix_Data_Sync = true,
	NoDeletePlayer = false,

	["Block Pet Gift"] = false,

	Collect_Cooldown = 90, -- cooldown to collect fruit

	["Low Cpu"] = true,
	["Auto Rejoin"] = false,

	["Rejoin When Update"] = false,
	["Limit Tree"] = {
		["Limit"] = 150,
		["Destroy Untill"] = 150,

		["Safe Tree"] = {
			"Moon Blossom",
			"Fossilight",
			"Hinomai",
			"Monoblooma",
			"Serenity",
			["Ember Lily"] = 10,
			["Sugar Apple"] = 10,
			["Burning Bud"] = 10,
			["Giant Pinecone"] = 10,
			["Elder Strawberry"] =10,
			["Beanstalk"] = 10,
			["Grand Tomato"] = 10,
			["King Cabbage"]= 10,
			["Romanesco"] = 2,
			["Tomato"] = 2,
			["Corn"] = 2,
			["Pumpkin"] = 2,
			["Watermelon"] = 2,
			["Strawberry"] = 2,
			["Coconut"] = 2,
			["Mushroom"] = 2,
			["Glowthorn"] = 2,
			["Apple"] = 2,
			["Sunbulb"] = 2,
			["Orange Tulip"] = 2,
			["Blueberry"] = 2,
			["Coconut"] = 2,
			["Cacao"] = 3,
			["Grape"] = 3,
			["Dragon Fruit"] = 2,
			["Grape"] = 2,
			["Cactus"] = 2,
			["Mango"] = 2,
			["Pepper"] = 2,
			["Lightshoot"] = 2,
			["Daffodil"] = 2,
		}
	},

	Seed = {
		Buy = {
			Mode = "Auto", -- Custom , Auto
			Custom = {
				"Carrot",
				"Bamboo",
				"Mushroom",
				"Tomato",
				"Strawberry",
				"Cactus",
				"Pepper",
				"Mango",
				"Dragon Fruit",
				"Cacao",
				"Beanstalk",
				"Grape",
				"Sugar Apple",
				"Burning Bud",
				"Orange Tulip",
				"Daffodil",
				"Mango",
				"Giant Pinecone",
				"Elder Strawberry",
				"Ember Lily",
				"Romanesco",
			}
		},
		Place = {
			Mode = "Lock", -- Select , Lock
			Select = {
				"Carrot",
				-- "Bamboo",
				-- "Mushroom",
				-- "Cacao",
				-- "Dragon Fruit",
				-- "Beanstalk",
				-- "Grape",
				-- "Sugar Apple",
				-- "Burning Bud",
				-- "Firefly Fern",
				-- "Boneboo",
				-- "Horned Dinoshroom",
				-- "Stonebite",
				-- "Paradise Petal",
				-- "Orange Tulip",
				-- "Daffodil",
				-- "Mango",
				-- "Giant Pinecone",
				-- "Hinomai",
				-- "Zen Rocks",
				-- "Monoblooma",
				-- "Serenity",
				-- "Taro Flower",
				-- "Dezen",
				-- "Lucky Bamboo",
				-- "Elder Strawberry",
				-- "Tall Asparagus",
				-- "Sugarglaze",
				-- "Onion",
				-- "Tomato",
				-- "Corn",
				-- "Pumpkin",
				-- "Watermelon",
				-- "Strawberry",
				-- "Cactus",
				-- "Pepper",
				-- "Mango",
				-- "Grand Tomato",
				-- "King Cabbage",
				-- "Romanesco",
				-- ["Tomato"] = 2,
				-- ["Corn"] = 2,
				-- ["Pumpkin"] = 2,
				-- ["Watermelon"] = 2,
				-- ["Strawberry"] = 2,
				-- ["Grape"] = 2,
				-- ["Cactus"] = 2,
				-- ["Mango"] = 2,
				-- ["Pepper"] = 2,
			},
			Lock = {
				"Maple Apple",
				"Sunflower",
				"Dragon Pepper",
				"Elephant Ears",
				"Moon Melon",
				"Easter Egg",
				"Moon Mango",
				"Bone Blossom",
				"Fossilight",
			}
		}
	},

	["Seed Pack"] = {
		Locked = {

		}
	},

	Events = {
		["Fairy Event"] = {
			Minimum_Money = 5_000_000, -- minimum money to start play this event
			Rewards_Item = {
				"Pet Shard Glimmering",
				"Enchanted Egg",
				"Mutation Spray Glimmering",
				"FairyPoints",
				"Fairy Targeter",
				"Enchanted Seed Pack",
			},
			Upgrade = {
				Mode = "Order", -- Order (mean will up on order), Chepest, Highest
				Order = { -- top upgrade first, not put mean not upgrade
					"Fairy Spawn Amount",
					"Loose Fairy Spawn Amount",
					"Glimmer Multiplier",
					"Fairy Event Duration",
				},
				Limit = {
					["Glimmer Multiplier"] = 5, -- max 10
					["Loose Fairy Spawn Amount"] = 10, -- max 10
					["Fairy Event Duration"] = 5, -- max 10
					["Fairy Spawn Amount"] = 9, -- max 9
				}
			}
		},
		MaxMoney_Restocks = 100_000_000,
		Shop = { -- delete -- to buy
			"Enchanted Chest",
			"Pet Shard Glimmering",
			"Enchanted Egg",
			"Enchanted Seed Pack",
			"Sprout Seed Pack",
			"Sprout Egg",
			"Silver Fertilizer",
			"Zen Egg",
			"Zen Seed Pack",
			"Koi",
			"Skyroot Chest",
			"Pet Shard GiantBean",
		},
		["Traveling Shop"] = {
			"Bee Egg",
			"Paradise Egg", 
			"Rare Summer Egg", 
			"Common Summer Egg"
		},
		Craft = {
			"Enchanted Chest",
			"Fairy Net",
			"Enchanted Egg",
			"Enchanted Seed Pack",
			"Anti Bee Egg",
			"Pet Shard GiantBean",
			"Sprout Egg",
		},
		Start_Do_Honey = 2_000_000 -- start trade fruit for honey at money
	},

	Gear = {
		Buy = { 
			"Grandmaster Sprinkler",
			"Master Sprinkler",
			"Godly Sprinkler",
			"Advanced Sprinkler",
			"Basic Sprinkler",
			"Lightning Rod",
			"Level Up Lollipop",
			"Levelup Lollipop",
			"Medium Treat",
			"Medium Toy",
		},
		Lock = {
			"Grandmaster Sprinkler",
			"Master Sprinkler",
			"Godly Sprinkler",
			"Advanced Sprinkler",
			"Basic Sprinkler",
			"Lightning Rod",
			"Level Up Lollipop",
			"Levelup Lollipop",
			"Mega Lollipop",
		},
	},

	Eggs = {
		Place = {
			"Enchanted Egg",
			"Zen Egg",
			"Paradise Egg",
			"Bug Egg",
			"Sprout Egg",
			"Primal Egg",
			"Dinosaur Egg",
			"Oasis Egg",
			"Anti Bee Egg",
			"Night Egg",
			"Bee Egg",
			"Gourmet Egg",
			"Mythical Egg",
			-- "Rare Summer Egg",
			"Rare Egg",
			-- "Common Egg",
		},
		Buy = {
			"Bug Egg",
			"Night Egg",
			"Bee Egg",
			"Anti Bee Egg",
			"Paradise Egg",
			"Oasis Egg",
			"Rare Egg",
			-- "Uncommon Egg",
			"Rare Summer Egg",
			"Common Egg",
		}
	},

	Pets = {
		MutationPet = {
			["Sunny-Side Chicken"] = { "Glimmering","Rainbow" },
			["Seal"] = { "Glimmering","Rainbow" }
		},
		["Auto Feed"] = true,
		["Start Delete Pet At"] = 50,
		Unfavorite_AllPet = false,
		Favorite_LockedPet = true,
		["Upgrade Slot"] = {
			["Pet"] = {
				["Ostrich"] = { 1, 75 ,1},
				["Tanchozuru"] = { 1, 45 ,2},
				["Kodama"] = { 1, 65 ,1},
				["Corrupted Kodama"] = { 1, 65 ,1},
				["Mochi Mouse"] = { 1, 60 ,1},
				["Junkbot"] = { 1, 45 ,1},
				["Koi"] = { 1, 60 ,1},
				["Hotdog Daschund"] = { 1, 75 ,1},
				["Sunny-Side Chicken"] = { 1, 85 ,1 , true},
				["Seal"] = { 1, 75 ,1 },
				["Rooster"] = { 1, 45 ,1 },
				["Lemon Lion"] = { 1, 60 ,1},
				["Glimmering Sprite"] = { 1, 70 , 1},
			},
			["Limit Upgrade"] = 5,
			["Equip When Done"] = {
				["Kodama"] = { 1, 70 },
				["Corrupted Kodama"] = { 1, 70 },
				["Koi"] = { 1, 70 },
				["Ostrich"] = { 1, 100, 1 }, -- 1 mean equip only 1 pet , 70 mean equip only level pet lower than 70 the one on the last mean first priority will ues first if possible 
				["Tanchozuru"] = { 1, 70 },
				["Mochi Mouse"] = { 1, 70 },
				["Junkbot"] = { 1, 70 },
				["Hotdog Daschund"] = { 1, 75 },
				["Sunny-Side Chicken"] = { 1, 100 ,1},
				["Seal"] = { 1, 75 ,1},
				["Rooster"] = { 1, 85 ,1},
				["Lemon Lion"] = { 1, 100 ,1},
				["Glimmering Sprite"] = { 1, 70 , 1},
			},
		},
		Locked_Pet_Age = 100, -- pet that age > 60 will lock
		Locked = {
			"Dragonfly",
			"Raccoon",
			"Queen Bee",
			"Disco Bee",
			"Butterfly",
			"Mimic Octopus",
			"Fennec Fox",
			"T-Rex",
			"Spinosaurus",
			"Kitsune",
			"Corrupted Kitsune",
			"French Fry Ferret",
			"Lobster Thermidor",
			"Brontosaurus",
			"Golden Goose",
			"Cockatrice",
			"Phoenix"
		},
		LockPet_Weight = 7, -- if Weight >= 10 they will locked,
		Instant_Sell = {		
			"Chicken",
			"Kiwi",
			"Blood Kiwi",
			"Dog",
			"Golden Lab",
			"Bunny",
			"Black Bunny",
			"Cat",
			"Orange Tabby",
			"Deer",
			"Spotted Deer",
			"Monkey",
			"Silver Monkey",
			"Pig",
			"Turtle",
			"Cow",
			"Polar Bear",
			"Panda",
			"Sea Otter",
			"Hedgehog",
			"Mole",
			"Frog",
			"Grey Mouse",
			"Brown Mouse",
			"Red Giant Ant",
			"Bee",
			"Honey Bee",
			"Wasp",
			"Tarantula Hawk",
			"Moth",
			"Peacock",
			"Meerkat",
			"Sand Snake",
			"Axolotl",
			"Flamingo",
			"Sea Turtle",
			"Orangutan",
			-- "Seal",
			"Moon Cat",
			"Hedgehog",
			"Mole",
			"Frog",
			"Echo Frog",
			"Night Owl",
			"Petal Bee",
			"Bear Bee",
			"Hyacinth Macaw",
			"Pterodactyl",
			"Triceratops",
			"Raptor",
			"Stegosaurus",
			"Ankylosaurus",
			"Pachycephalosaurus",
			"Iguanodon",
			"Parasaurolophus",
			"Caterpillar",
			"Snail",
			"Giant Ant",
			"Praying Mantis",
			"Shiba Inu",
			"Tanuki",
			"Nihonzaru",
			"Kappa",
			"Capybara",
			"Maneki-neko",
			"Football",
			"Scarlet Macaw",
			"Bagel Bunny",
			"Pancake Mole",
			"Sushi Bear",
			"Toucan",
			"Bacon Pig",
			"Spaghetti Sloth",
			"Gorilla Chef",
			"Dairy Cow",
			"Jackalope",
			"Seedling",
			"Golem",
			"Mandrake",
			"Elk",
			"Ladybug",
			"Pixie",
			"Imp",
		}
	},

	Webhook = {
		UrlPet = getgenv().Discord,
		UrlSeed = getgenv().Discord,
		PcName = getgenv().PCAYA,

		Noti = {
			Seeds = {
			},
			SeedPack = {
			},
			Pets = {
				"Dragonfly",
				"Raccoon",
				"Queen Bee",
				"Disco Bee",
				"Butterfly",
				"Mimic Octopus",
				"Fennec Fox",
				"T-Rex",
				"Spinosaurus",
				"Kitsune",
				"Corrupted Kitsune",
				"French Fry Ferret",
				"Golden Goose",
				"Cockatrice",
				"Phoenix"
			},
			Pet_Weight_Noti = true,
		}
	},
}
License = getgenv().KeyAYA
loadstring(game:HttpGet('https://raw.githubusercontent.com/Real-Aya/Loader/main/Init.lua'))()
