getgenv().ConfigsKaitun = {
	Beta_Fix_Data_Sync = true,
	NoDeletePlayer = false,

	["Block Pet Gift"] = false,

	Collect_Cooldown = 90, -- cooldown to collect fruit

	["Low Cpu"] = true,
	["Auto Rejoin"] = false,

	["Rejoin When Update"] = false,
	["Limit Tree"] = {
		["Limit"] = 150,
		["Destroy Untill"] = 150,

		["Safe Tree"] = {
			"Moon Blossom",
			"Fossilight",
			"Hinomai",
			"Monoblooma",
			"Serenity",
			["Cacao"] = 3,
			["Grape"] = 3,
			["Dragon Fruit"] = 3,
			["Ember Lily"] = 10,
			["Sugar Apple"] = 10,
			["Burning Bud"] = 10,
			["Giant Pinecone"] = 10,
			["Elder Strawberry"] =10,
			["Beanstalk"] = 10,
			["Tomato"] = 2,
			["Corn"] = 2,
			["Pumpkin"] = 2,
			["Watermelon"] = 2,
			["Strawberry"] = 2,
			["Grape"] = 2,
			["Cactus"] = 2,
			["Mango"] = 2,
			["Pepper"] = 2,
			["Grand Tomato"] = 10,
			["King Cabbage"]= 10,
			"Romanesco",
		}
	},

	Seed = {
		Buy = {
			Mode = "Custom", -- Custom , Auto
			Custom = {
				"Carrot",
				"Bamboo",
				"Mushroom",
				"Tomato",
				-- "Corn",
				-- "Pumpkin",
				-- "Watermelon",
				"Strawberry",
				"Cactus",
				"Pepper",
				"Mango",
				"Dragon Fruit",
				"Cacao",
				"Beanstalk",
				"Grape",
				"Sugar Apple",
				"Burning Bud",
				"Orange Tulip",
				"Daffodil",
				"Mango",
				"Giant Pinecone",
				"Elder Strawberry",
				"Ember Lily",
				"Romanesco",
			}
		},
		Place = {
			Mode = "Select", -- Select , Lock
			Select = {
				"Carrot",
				"Bamboo",
				"Mushroom",
				"Cacao",
				"Dragon Fruit",
				"Beanstalk",
				"Grape",
				"Sugar Apple",
				"Burning Bud",
				"Firefly Fern",
				"Boneboo",
				"Horned Dinoshroom",
				"Stonebite",
				"Paradise Petal",
				"Orange Tulip",
				"Daffodil",
				"Mango",
				"Giant Pinecone",
				"Hinomai",
				"Zen Rocks",
				"Monoblooma",
				"Serenity",
				"Taro Flower",
				"Dezen",
				"Lucky Bamboo",
				"Elder Strawberry",
				"Tall Asparagus",
				"Sugarglaze",
				"Onion",
				"Tomato",
				"Corn",
				"Pumpkin",
				"Watermelon",
				"Strawberry",
				"Cactus",
				"Pepper",
				"Mango",
				"Grand Tomato",
				"King Cabbage",
				"Romanesco",
				-- ["Tomato"] = 2,
				-- ["Corn"] = 2,
				-- ["Pumpkin"] = 2,
				-- ["Watermelon"] = 2,
				-- ["Strawberry"] = 2,
				-- ["Grape"] = 2,
				-- ["Cactus"] = 2,
				-- ["Mango"] = 2,
				-- ["Pepper"] = 2,
			},
			Lock = {
			}
		}
	},

	["Seed Pack"] = {
		Locked = {

		}
	},

	Events = {
		Dino = true,
		["Bean Event"] = {
			Minimum_Money = 10_000_000, -- minimum money to start play this event
		},
		MaxMoney_Restocks = 100_000_000,
		Restocks_When_Come = { -- will restock when Sprout Egg come on shop
			"Sprout Egg",
		},
		Shop = { -- delete -- to buy
			"Sprout Seed Pack",
			"Sprout Egg",
			-- "Mandrake",
			"Silver Fertilizer",
			-- "Canary Melon",
			-- "Amberheart",
			"Zen Egg",
			"Zen Seed Pack",
			"Koi",
			"Skyroot Chest",
			"Pet Shard GiantBean",
		},
		["Traveling Shop"] = {
			"Bee Egg",
		},
		Craft = {
			"Ancient Seed Pack",
			"Anti Bee Egg",
			"Primal Egg",
			"Pet Shard GiantBean",
			"Sprout Egg",
		},
		Start_Do_Honey = 2_000_000 -- start trade fruit for honey at money
	},

	Gear = {
		Buy = { 
			"Grandmaster Sprinkler",
			"Master Sprinkler",
			"Godly Sprinkler",
			"Advanced Sprinkler",
			"Basic Sprinkler",
			"Lightning Rod",
			"Level Up Lollipop",
			"Medium Treat",
			"Medium Toy",
		},
		Lock = {
			"Grandmaster Sprinkler",
			"Master Sprinkler",
			"Godly Sprinkler",
			"Advanced Sprinkler",
			"Basic Sprinkler",
			"Lightning Rod",
			"Level Up Lollipop",
		},
	},

	Eggs = {
		Place = {
			"Sprout Egg",
			"Primal Egg",
			"Dinosaur Egg",
			"Zen Egg",
			"Paradise Egg",
			"Oasis Egg",
			"Anti Bee Egg",
			"Night Egg",
			"Bug Egg",
			"Bee Egg",
			"Gourmet Egg",
			"Mythical Egg",
			"Rare Summer Egg",
			-- "Rare Egg",
			-- "Common Egg",
		},
		Buy = {
			"Bug Egg",
			"Night Egg",
			"Bee Egg",
			"Anti Bee Egg",
			"Paradise Egg",
			"Oasis Egg",
			"Rare Egg",
			-- "Uncommon Egg",
			"Rare Summer Egg",
			"Common Egg",
		}
	},

	Pets = {
		["Auto Feed"] = true,
		["Start Delete Pet At"] = 40,
		Unfavorite_AllPet = false,
		Favorite_LockedPet = true,
		["Upgrade Slot"] = {
			["Pet"] = {
				["Ostrich"] = { 1, 75 ,1},
				["Tanchozuru"] = { 1, 45 ,2},
				["Kodama"] = { 1, 65 ,1},
				["Corrupted Kodama"] = { 1, 65 ,1},
				["Mochi Mouse"] = { 1, 60 ,1},
				["Junkbot"] = { 1, 45 ,1},
				["Koi"] = { 1, 60 ,1},
				["Hotdog Daschund"] = { 1, 60 ,1},
				["Sunny-Side Chicken"] = { 1, 75 ,1 , true},
				["Seal"] = { 1, 75 ,1 , true},
			},
			["Limit Upgrade"] = 5,
			["Equip When Done"] = {
				["Kodama"] = { 1, 70 },
				["Corrupted Kodama"] = { 1, 70 },
				["Koi"] = { 1, 70 },
				["Ostrich"] = { 1, 100, 1 }, -- 1 mean equip only 1 pet , 70 mean equip only level pet lower than 70 the one on the last mean first priority will ues first if possible 
				["Tanchozuru"] = { 1, 70 },
				["Mochi Mouse"] = { 1, 70 },
				["Junkbot"] = { 1, 70 },
				["Hotdog Daschund"] = { 1, 70 },
				["Sunny-Side Chicken"] = { 1, 100 ,1},
				["Seal"] = { 1, 100 ,1},
			},
		},
		Locked_Pet_Age = 100, -- pet that age > 60 will lock
		Locked = {
			"Dragonfly",
			"Raccoon",
			"Queen Bee",
			"Disco Bee",
			"Butterfly",
			"Mimic Octopus",
			"Fennec Fox",
			"T-Rex",
			"Spinosaurus",
			"Kitsune",
			"Corrupted Kitsune",
			"French Fry Ferret",
			"Lobster Thermidor",
			"Brontosaurus",
			"Golden Goose",
		},
		LockPet_Weight = 7, -- if Weight >= 10 they will locked,
		Instant_Sell = {		
			"Chicken",
			"Rooster",
			"Kiwi",
			"Blood Kiwi",
			"Dog",
			"Golden Lab",
			"Bunny",
			"Black Bunny",
			"Cat",
			"Orange Tabby",
			"Deer",
			"Spotted Deer",
			"Monkey",
			"Silver Monkey",
			"Pig",
			"Turtle",
			"Cow",
			"Polar Bear",
			"Panda",
			"Sea Otter",
			"Hedgehog",
			"Mole",
			"Frog",
			"Grey Mouse",
			"Brown Mouse",
			"Red Giant Ant",
			"Bee",
			"Honey Bee",
			"Wasp",
			"Tarantula Hawk",
			"Moth",
			"Peacock",
			"Meerkat",
			"Sand Snake",
			"Axolotl",
			"Flamingo",
			"Sea Turtle",
			"Orangutan",
			-- "Seal",
			"Moon Cat",
			"Hedgehog",
			"Mole",
			"Frog",
			"Echo Frog",
			"Night Owl",
			"Petal Bee",
			"Bear Bee",
			"Hyacinth Macaw",
			"Pterodactyl",
			"Triceratops",
			"Raptor",
			"Stegosaurus",
			"Ankylosaurus",
			"Pachycephalosaurus",
			"Iguanodon",
			"Parasaurolophus",
			"Caterpillar",
			"Snail",
			"Giant Ant",
			"Praying Mantis",
			"Shiba Inu",
			"Tanuki",
			"Nihonzaru",
			"Kappa",
			"Capybara",
			"Maneki-neko",
			"Football",
			"Scarlet Macaw",
			"Bagel Bunny",
			"Pancake Mole",
			"Sushi Bear",
			"Toucan",
			"Bacon Pig",
			"Spaghetti Sloth",
			"Gorilla Chef",
			"Dairy Cow",
			"Jackalope",
			"Seedling",
			"Golem",
		}
	},

	Webhook = {
		UrlPet = getgenv().Discord,
		UrlSeed = getgenv().Discord,
		PcName = getgenv().PCAYA,

		Noti = {
			Seeds = {
			},
			SeedPack = {
			},
			Pets = {
				"Dragonfly",
				"Raccoon",
				"Queen Bee",
				"Disco Bee",
				"Butterfly",
				"Mimic Octopus",
				"Fennec Fox",
				"T-Rex",
				"Spinosaurus",
				"Kitsune",
				"Corrupted Kitsune",
				"French Fry Ferret",
				"Golden Goose",
				"Griffin"
			},
			Pet_Weight_Noti = true,
		}
	},
}
License = getgenv().KeyAYA
loadstring(game:HttpGet('https://raw.githubusercontent.com/Real-Aya/Loader/main/Init.lua'))()
