repeat task.wait() until game:IsLoaded()
repeat task.wait() until game.Players
repeat task.wait() until game.Players.LocalPlayer
_G.Settings = {
    PlantSettings = {
        Limit = 200,
        Plant = {
            ["Carrot"] = 50,
            ["Bamboo"] = 50,
            ["Mushroom"] = 3,
            ["Cacao"] = 3,
            ["Beanstalk"] = 3,
            ["Grape"] = 3,
            ["Sugar Apple"] = 3,
            ["Burning Bud"] = 3,
        },
        Destroy = {
            WhenMoney = 50000,
            Plant = {
                "Strawberry"
            }
        }
    },
    SeedsSetting = {
        "Carrot",
    		"Bamboo",
    		"Mushroom",
    		"Cacao",
    		"Beanstalk",
    		"Grape",
    		"Sugar Apple",
    		"Burning Bud",
    },
    EggSettings = {
        StartBuyEggWhen = 150000,
        SelectEggs = {
            "Bug Egg",
        		"Night Egg",
        		"Bee Egg",
        		"Anti Bee Egg",
        		"Paradise Egg",
        		"Oasis Egg",
        		"Rare Summer Egg",
        		"Uncommon Egg",
        		"Common Egg",
        },
    },
    Webhook = getgenv().Discord,
    UpgradeEggSlots = 2,
    UpgradePetSlots = 2,
    PetSettings = {
        Sell = {
            "Chicken",
        		"Rooster",
        		"Kiwi",
        		"Blood Kiwi",
        		"Dog",
        		"Golden Lab",
        		"Bunny",
        		"Black Bunny",
        		"Cat",
        		"Orange Tabby",
        		"Deer",
        		"Spotted Deer",
        		"Monkey",
        		"Silver Monkey",
        		"Pig",
        		"Turtle",
        		"Cow",
        		"Polar Bear",
        		"Panda",
        		"Sea Otter",
        		"Hedgehog",
        		"Mole",
        		"Frog",
        		"Grey Mouse",
        		"Brown Mouse",
        		"Red Giant Ant",
        		"Bee",
        		"Honey Bee",
        		"Wasp",
        		"Tarantula Hawk",
        		"Moth",
        		"Ostrich",
        		"Peacock",
        		"Capybara",
        		"Meerkat",
        		"Sand Snake",
        		"Axolotl",
        		"Flamingo",
        		"Sea Turtle",
        		"Orangutan",
        		"Seal",
        		"Moon Cat",
        		"Hedgehog",
        		"Mole",
        		"Frog",
        		"Echo Frog",
        		"Night Owl",
        		"Petal Bee",
        		"Bear Bee",
        		"Toucan",
        		"Hyacinth Macaw",
        		"Pterodactyl",
        		"Triceratops",
        		"Raptor",
        		"Stegosaurus",
        },
        UpgradeSlots = {
            "Chicken", "Rooster"
        },
        Events = {
            "Chicken",
        		"Rooster",
        		"Kiwi",
        		"Blood Kiwi",
        		"Dog",
        		"Golden Lab",
        		"Bunny",
        		"Black Bunny",
        		"Cat",
        		"Orange Tabby",
        		"Deer",
        		"Spotted Deer",
        		"Monkey",
        		"Silver Monkey",
        		"Pig",
        		"Turtle",
        		"Cow",
        		"Polar Bear",
        		"Panda",
        		"Sea Otter",
        		"Hedgehog",
        		"Mole",
        		"Frog",
        		"Grey Mouse",
        		"Brown Mouse",
        		"Red Giant Ant",
        		"Bee",
        		"Honey Bee",
        		"Wasp",
        		"Tarantula Hawk",
        		"Moth",
        		"Ostrich",
        		"Peacock",
        		"Capybara",
        		"Meerkat",
        		"Sand Snake",
        		"Axolotl",
        		"Flamingo",
        		"Sea Turtle",
        		"Orangutan",
        		"Seal",
        		"Moon Cat",
        		"Hedgehog",
        		"Mole",
        		"Frog",
        		"Echo Frog",
        		"Night Owl",
        		"Petal Bee",
        		"Bear Bee",
        		"Toucan",
        		"Hyacinth Macaw",
        		"Pterodactyl",
        		"Triceratops",
        		"Raptor",
        		"Stegosaurus",
        },
        Equip = {
            "Chicken",
        		"Rooster",
        		"Kiwi",
        		"Blood Kiwi",
        		"Capybara",
        		"Toucan",
        		"Ostrich",
        }
    },
    CraftSettings = {
        Enabled = true,
        Workbench = "Ancient Seed Pack",
        SeedEventWorkbench = "Anti Bee Egg"
    },
    PrehistoricEvents = {
        ClaimReward = true,
        PetToTrade = {
            "Chicken",
        		"Rooster",
        		"Kiwi",
        		"Blood Kiwi",
        		"Dog",
        		"Golden Lab",
        		"Bunny",
        		"Black Bunny",
        		"Cat",
        		"Orange Tabby",
        		"Deer",
        		"Spotted Deer",
        		"Monkey",
        		"Silver Monkey",
        		"Pig",
        		"Turtle",
        		"Cow",
        		"Polar Bear",
        		"Panda",
        		"Sea Otter",
        		"Hedgehog",
        		"Mole",
        		"Frog",
        		"Grey Mouse",
        		"Brown Mouse",
        		"Red Giant Ant",
        		"Bee",
        		"Honey Bee",
        		"Wasp",
        		"Tarantula Hawk",
        		"Moth",
        		"Ostrich",
        		"Peacock",
        		"Capybara",
        		"Meerkat",
        		"Sand Snake",
        		"Axolotl",
        		"Flamingo",
        		"Sea Turtle",
        		"Orangutan",
        		"Seal",
        		"Moon Cat",
        		"Hedgehog",
        		"Mole",
        		"Frog",
        		"Echo Frog",
        		"Night Owl",
        		"Petal Bee",
        		"Bear Bee",
        		"Toucan",
        		"Hyacinth Macaw",
        		"Pterodactyl",
        		"Triceratops",
        		"Raptor",
        		"Stegosaurus",
        }
    },
    GearStocksBuy = {
        "Godly Sprinkler",
    		"Master Sprinkler",
    },
    UseSeedPack = true,
    CropSettings = {
        ['DelayTime'] = 5,
        ['TimeCrop'] = 5
    }
}
getgenv().Script_Mode = "Kaitun_Script"
loadstring(game:HttpGet("https://raw.githubusercontent.com/xshiba/MaruBitkub/main/Mobile.lua"))()
